### PR TITLE
Add CFX and Drip definition

### PR DESCRIPTION
**Pull request by darwintree**
This change is [Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-utils/1)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 3 of 4 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-utils/1)* status: all files reviewed, 3 unresolved discussions (waiting on @darwintree)

___
*[`tests/test_token_unit.py` line 33 at r2](https://reviewable.io/reviews/conflux-fans/cfx-utils/1#-NDrISM7BssiWnuApImG:-NDrISM7BssiWnuApImH:b-dn5t4u) ([raw file](https://github.com/conflux-fans/cfx-utils/blob/5983b815e4949977219826077cb140b5404ae085/tests/test_token_unit.py#L33)):*
> ```Python
>     Drip.base_unit
>     Drip(10**18)
>     Drip(1)
> ```

Two Drip(1) here 
___
*[`tests/test_token_unit.py` line 98 at r2](https://reviewable.io/reviews/conflux-fans/cfx-utils/1#-NDwJYVG3K-gJt54KczW:-NDwJYVG3K-gJt54KczX:b-qgluqm) ([raw file](https://github.com/conflux-fans/cfx-utils/blob/5983b815e4949977219826077cb140b5404ae085/tests/test_token_unit.py#L98)):*
> ```Python
> 
>     assert_type_and_value(tmp, Drip, 1 + 10**18)
>     tmp = Drip(1) + Drip(1)
> ```

it seems this line can be omitted 
___
*[`tests/test_token_unit.py` line 171 at r2](https://reviewable.io/reviews/conflux-fans/cfx-utils/1#-NDwHbij2-tu89ulkusk:-NDwHbim6St117VAt6jk:b-6czsgd) ([raw file](https://github.com/conflux-fans/cfx-utils/blob/5983b815e4949977219826077cb140b5404ae085/tests/test_token_unit.py#L171)):*
> ```Python
>     # Drip(10) > 5 and 5 > CFX(2)
>     # However, 5 has different meanings in different context, Users should be careful to use chained comparison on token values
>     assert Drip(10) > 5 > CFX(2)
> ```

this is a confusing and easy-to-lead error, maybe we need to document it well

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-utils/1)* status: 11 of 16 files reviewed, 3 unresolved discussions (waiting on @Pana)

___
*[`tests/test_token_unit.py` line 33 at r2](https://reviewable.io/reviews/conflux-fans/cfx-utils/1#-NDrISM7BssiWnuApImG:-NF71G1M1aM9Z351EkcQ:b-896fix) ([raw file](https://github.com/conflux-fans/cfx-utils/blob/5983b815e4949977219826077cb140b5404ae085/tests/test_token_unit.py#L33)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

Two Drip(1) here 
</blockquote></details>

Done.
___
*[`tests/test_token_unit.py` line 98 at r2](https://reviewable.io/reviews/conflux-fans/cfx-utils/1#-NDwJYVG3K-gJt54KczW:-NF6iNUhBInnfB6Gf0Ox:b9agbv7) ([raw file](https://github.com/conflux-fans/cfx-utils/blob/5983b815e4949977219826077cb140b5404ae085/tests/test_token_unit.py#L98)):*
> This line is used to check type hints. The python language server needs to correctly infer the type of `tmp`, and we need to make sure the followings:

``` python
tmp = Drip(1) + CFX(1) # should infer tmp as Drip
tmp = Drip(1) + Drip(1) # should infer tmp as Drip
tmp = CFX(1) + Drip(1) # should infer tmp as Drip
```

Currently, the static type check codes are added
___
*[`tests/test_token_unit.py` line 171 at r2](https://reviewable.io/reviews/conflux-fans/cfx-utils/1#-NDwHbij2-tu89ulkusk:-NF71RDkARHSTyIlypqI:b3sijff) ([raw file](https://github.com/conflux-fans/cfx-utils/blob/5983b815e4949977219826077cb140b5404ae085/tests/test_token_unit.py#L171)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

this is a confusing and easy-to-lead error, maybe we need to document it well
</blockquote></details>

Yeah this is confusing. And it is under consideration whether to disallow token units to directly compare with a number.

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-utils/1)* status: 9 of 16 files reviewed, 3 unresolved discussions (waiting on @Pana)

___
*[`tests/test_token_unit.py` line 171 at r2](https://reviewable.io/reviews/conflux-fans/cfx-utils/1#-NDwHbij2-tu89ulkusk:-NF8KQ7r7-CYvgrGBizy:b8e3q6s) ([raw file](https://github.com/conflux-fans/cfx-utils/blob/5983b815e4949977219826077cb140b5404ae085/tests/test_token_unit.py#L171)):*
<details><summary><i>Previously, darwintree wrote…</i></summary><blockquote>

Yeah this is confusing. And it is under consideration whether to disallow token units to directly compare with a number.
</blockquote></details>

Now directly compare a token unit and a number is not allowed

**Review by Pana — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-utils/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Pull request merged**
